FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

WORKDIR /app

COPY FrontendTask/*.csproj .
COPY Protos/ ../Protos/
RUN dotnet restore

COPY FrontendTask/ .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS run

WORKDIR /app
COPY --from=build /app/out/ .

EXPOSE 80

ENTRYPOINT [ "dotnet", "FrontendTask.dll" ]
